Teach in-buildddir utils to validate network
This commit leverages the existence of an `$ALL_CONDUITS` variable in
`configure` to add validation of `UPCXX_NETWORK` (and its many
aliases, including command-line of `upcxx`) to the generated `upcxx`
and `upcxx-meta` in `$builddir/bin`.

Since the scripts are generated prior to configuring GASNet, this new
logic is only effective at catching networks that are "unknown".
However, the existing GASNet behavior for conduits which are known but
were *not* detected at configure time is (IMO) already sufficient:
```
$ UPCXX_NETWORK=ucx ./bin/upcxx-meta DUMP
INFO: may need to build the required runtime.  Please be patient.
make[1]: Nothing to be done for `/Users/phargrov/upcxx/B/Makefile'.
make[5]: `gasnet-ucx-par.pc' is up to date.
ERROR: ucx-conduit support was not detected at configure time
       try re-running configure with --enable-ucx
make[5]: *** [do-error] Error 1
make[4]: *** [par] Error 2
make[3]: *** [gasnet-single] Error 2
make[2]: *** [upcxx.assert0.optlev3.dbgsym0.gasnet_par.ucx/libupcxx.a] Error 2
make[1]: *** [upcxx-meta] Error 2
make: *** [upcxx-meta] Error 2
upcxx-meta: ERROR: build of the required runtime failed.
```